name: "package-version"
description: "Extracts version from package.json to an environment variable"
branding:
  color: gray-dark
  icon: package
author: "nyaa8"
inputs:
  path:
    description: "package.json location"
    required: false
  follow-symlinks:
    description: "Indicates whether to follow symbolic links"
    required: false
    default: "true"
runs:
  using: "node16"
  main: "dist/index.js"

# vim: ts=2 sw=2 expandtab
